-- ============================================================================
-- LoanTracker — Seed Data (optional)
-- ============================================================================
-- This file inserts sample data for development/testing.
--
-- IMPORTANT: Replace the placeholder user_id with a real auth.users UUID
-- after you've created a test account via the app's registration screen.
--
-- You can find your user_id in the Supabase Dashboard under:
--   Authentication → Users → click on your user → copy the UUID.
-- ============================================================================

-- Replace this with your actual user UUID ↓
-- DO NOT run this seed in production.

/*

-- Example: two loans and their payment schedules

-- 1. A credit loan (user owes money to Ramesh)
INSERT INTO loans (user_id, type, person_name, person_phone, principal_amount, rate_of_interest, payment_day_of_month, start_date, tenure_months, remaining_amount, notes)
VALUES (
  'YOUR-USER-UUID-HERE',
  'credit',
  'Ramesh Kumar',
  '+91 98765 43210',
  50000.00,
  12.00,
  5,
  '2026-01-01',
  6,
  53000.00,  -- 50000 + (50000 * 12 * 6) / (12 * 100) = 53000
  'Personal loan for home renovation'
);

-- 2. A debit loan (user lent money to Priya)
INSERT INTO loans (user_id, type, person_name, person_phone, principal_amount, rate_of_interest, payment_day_of_month, start_date, tenure_months, remaining_amount, notes)
VALUES (
  'YOUR-USER-UUID-HERE',
  'debit',
  'Priya Sharma',
  '+91 91234 56789',
  25000.00,
  10.00,
  15,
  '2026-02-01',
  4,
  25833.33,  -- 25000 + (25000 * 10 * 4) / (12 * 100) = 25833.33
  'Lent for medical expenses'
);

-- Payment schedules would normally be auto-generated by the app.
-- If you need sample payments, insert them manually or use the app's
-- "Add Loan" form which handles schedule generation automatically.

*/
